window.INITIAL_PROPERTIES = [
  {
    id: 'prop_01',
    hostId: 'host_001',
    title: 'The Solang Valley Glass Chalet & Cedar Spa',
    tagline: 'Secluded Himalayan glass chalet with snow peak views.',
    description: 'Nestled amidst deodar forests in Manali, this handcrafted cedar and glass chalet offers unobstructed 360-degree views of Solang snow peaks. Features a private wood-fired cedar tub, radiant floor heating, open fireplace, and traditional Himachali dining.',
    price: 16500,
    cleaning: 2500,
    rating: 4.98,
    reviews: 52,
    city: 'Manali, Himachal Pradesh',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Vikramaditya Thorne',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    amenities: ['Cedar Wood Hot Tub', 'Himalayan Peak View', 'Full Himachali Kitchen', 'Stone Fireplace', 'High-Speed Satellite Wi-Fi', 'EV Charger'],
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_02',
    hostId: 'host_002',
    title: 'Portuguese Heritage Beachfront Villa & Saltwater Pool',
    tagline: 'Private oceanfront sanctuary on Vagator cliffside.',
    description: 'Restored 19th-century Portuguese estate overlooking Arabian Sea waters in North Goa. Features a cliffside infinity saltwater pool, azulejo tile courtyards, teakwood sundecks, and direct access to a private cove.',
    price: 28000,
    cleaning: 3500,
    rating: 4.96,
    reviews: 41,
    city: 'Goa, India',
    specs: { guests: 6, bedrooms: 3, beds: 3, baths: 3.5 },
    hostName: 'Ananya Deshmukh',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    amenities: ['Infinity Saltwater Pool', 'Arabian Sea Sunset Deck', 'Private Cove Access', 'Goan Seafood Butler'],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_03',
    hostId: 'host_003',
    title: 'The Lake Pichola Royal Haveli & Courtyard',
    tagline: 'Historic royal suite with Lake Pichola palace views.',
    description: 'Immerse yourself in Rajasthani royalty at this restored 300-year-old lakeside haveli in Udaipur. Features Jharokha stone balconies framing City Palace views, marble baths, and private boat transfers.',
    price: 22500,
    cleaning: 3000,
    rating: 4.97,
    reviews: 68,
    city: 'Udaipur, Rajasthan',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Maharana Ranveer Singh',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Lake Pichola Palace View', 'Carved Stone Jharokhas', 'Private Shikara Boat', 'Royal Thali Chef'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_04',
    hostId: 'host_004',
    title: 'Munnar Cloud Valley Estate & Tea Plantation Treehouse',
    tagline: 'Elevated wooden sanctuary above mist-covered tea gardens.',
    description: 'Surrounded by 40 acres of private organic tea plantations in Munnar, Kerala. Wake up above cloud cover with Ayurvedic breakfast served on your wrap-around teak deck.',
    price: 14500,
    cleaning: 2000,
    rating: 4.99,
    reviews: 39,
    city: 'Munnar, Kerala',
    specs: { guests: 3, bedrooms: 1, beds: 1, baths: 1 },
    hostName: 'Dr. Kurien Menon',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Tea Plantation Trek', 'Ayurvedic Kitchen', 'Cloud Valley Deck', 'Firewood Lounge'],
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_05',
    hostId: 'host_001',
    title: 'Coorg Teakwood Estate Villa & Private Waterfall',
    tagline: 'Private coffee plantation sanctuary with private waterfall access.',
    description: 'Experience lush rainforest luxury at this 50-acre private coffee and spice plantation villa in Coorg. Features teakwood verandas, private waterfall plunge pools, organic Kodava dining, and estate birdwatching treks.',
    price: 19500,
    cleaning: 2800,
    rating: 4.97,
    reviews: 34,
    city: 'Coorg, Karnataka',
    specs: { guests: 6, bedrooms: 3, beds: 3, baths: 3 },
    hostName: 'Deviah Bopanna',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    amenities: ['Private Waterfall', 'Coffee Estate Trek', 'Teakwood Veranda', 'Kodava Butler'],
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_06',
    hostId: 'host_005',
    title: 'Dal Lake Royal Walnut Wood Houseboat',
    tagline: 'Historic cedar wood houseboat floating on calm Dal Lake waters.',
    description: 'Step into traditional Kashmiri elegance on this carved walnut wood luxury houseboat docked at Dal Lake, Srinagar. Features hand-woven Silk carpets, heated Khatamband ceilings, private Shikara rides, and Wazwan feasts.',
    price: 21000,
    cleaning: 2500,
    rating: 4.99,
    reviews: 58,
    city: 'Srinagar, Jammu & Kashmir',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Tariq Ahmed Mir',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Dal Lake Sunset View', 'Private Shikara Rides', 'Kashmiri Wazwan Chef', 'Heated Khatamband Rooms'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_07',
    hostId: 'host_003',
    title: 'Amer Fort Heritage Villa & Royal Courtyard',
    tagline: 'Pink City heritage courtyard villa overlooking Amer Fort.',
    description: 'A serene oasis in the heart of Jaipur. Built with traditional red sandstone, this restored heritage haveli features a marble courtyard pool, rooftop peacock terrace, private puppet performances, and authentic Rajasthani hospitality.',
    price: 24500,
    cleaning: 3200,
    rating: 4.95,
    reviews: 47,
    city: 'Jaipur, Rajasthan',
    specs: { guests: 6, bedrooms: 3, beds: 3, baths: 3 },
    hostName: 'Rani Sunita Kumari',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    amenities: ['Amer Fort View Deck', 'Marble Courtyard Pool', 'Rooftop Lounge', 'Rajasthani Thali'],
    images: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_08',
    hostId: 'host_006',
    title: 'Ganges Cliffside Glass Villa & Yoga Shala',
    tagline: 'Peaceful Himalayan retreat overlooking the turquoise Ganges.',
    description: 'Perched on a quiet cliff above the holy Ganges river in Rishikesh. Features private open-air yoga shala, organic Sattvic dining, infinity sound-bath pool, and evening Ganga Aarti concierge transfers.',
    price: 17500,
    cleaning: 2200,
    rating: 4.98,
    reviews: 62,
    city: 'Rishikesh, Uttarakhand',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Swami Anand Giri',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Ganges River View', 'Private Yoga Shala', 'Sattvic Kitchen', 'Cliffside Deck'],
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_09',
    hostId: 'host_004',
    title: 'Vembanad Backwaters Luxury Kettuvallam',
    tagline: 'Private luxury houseboat cruising the serene Kerala backwaters.',
    description: 'Drift through palm-fringed canals on this traditional eco-luxury wooden Kettuvallam houseboat in Alleppey. Includes private chef preparing fresh Karimeen fish curry, sun deck, and village canoe excursions.',
    price: 23000,
    cleaning: 2500,
    rating: 4.97,
    reviews: 49,
    city: 'Alleppey, Kerala',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Captain Thomas Varghese',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    amenities: ['Backwater Cruise', 'Kerala Seafood Chef', 'Teakwood Sun Deck', 'Canoe Excursions'],
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_10',
    hostId: 'host_001',
    title: 'Shimla Colonial Heritage Manor & Apple Orchard',
    tagline: 'British-era stone manor surrounded by blooming apple orchards.',
    description: 'High in the pine forests of Shimla, this restored 1920s British colonial estate features antique fireplaces, bay window reading nooks, private apple picking in autumn, and panoramic Himalayan mountain views.',
    price: 18900,
    cleaning: 2600,
    rating: 4.96,
    reviews: 38,
    city: 'Shimla, Himachal Pradesh',
    specs: { guests: 5, bedrooms: 3, beds: 3, baths: 2.5 },
    hostName: 'Major Gen. Gurpreet Singh',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    amenities: ['Apple Orchard Pick', 'Colonial Fireplaces', 'Mountain Panorama', 'High Tea Veranda'],
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_11',
    hostId: 'host_007',
    title: 'French Quarter Colonial Villa & Courtyard Pool',
    tagline: 'Charming yellow French colonial villa in White Town.',
    description: 'Located in the peaceful French Quarter of Pondicherry. Features high arched ceilings, yellow mustard lime-wash walls, private dip pool, bougainvillea balconies, and complimentary vintage bicycles.',
    price: 15800,
    cleaning: 2000,
    rating: 4.94,
    reviews: 53,
    city: 'Pondicherry, India',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Claire & Pierre Dupont',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    amenities: ['French White Town', 'Private Dip Pool', 'Vintage Bicycles', 'French Bakery Breakfast'],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_12',
    hostId: 'host_001',
    title: 'Mullayanagiri Peak Coffee Glass Cottage',
    tagline: 'Glass cottage overlooking Western Ghats coffee mountains.',
    description: 'Perched on the slopes of Mullayanagiri peak in Chikmagalur. Enjoy panoramic views of mist-clad Western Ghats, private espresso tasting tours, heated Jacuzzi, and campfires under the stars.',
    price: 16200,
    cleaning: 2200,
    rating: 4.97,
    reviews: 29,
    city: 'Chikmagalur, Karnataka',
    specs: { guests: 4, bedrooms: 2, beds: 2, baths: 2 },
    hostName: 'Aditya Hegde',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    amenities: ['Western Ghats View', 'Private Jacuzzi', 'Espresso Plantation Tour', 'Campfire Lounge'],
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_13',
    hostId: 'host_003',
    title: 'Thar Desert Royal Sand Dunes Haveli & Tents',
    tagline: 'Golden sandstone haveli & private desert safari.',
    description: 'Located near the Sam sand dunes in Jaisalmer. Experience golden desert sunsets, camel safaris, stargazing dinners under clear desert skies, and royal Manganiyar folk musician performances.',
    price: 20500,
    cleaning: 2700,
    rating: 4.98,
    reviews: 45,
    city: 'Jaisalmer, Rajasthan',
    specs: { guests: 6, bedrooms: 3, beds: 3, baths: 3 },
    hostName: 'Bhati Rawal Singh',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Thar Desert Dune Safari', 'Stargazing Lounge', 'Folk Music Dinners', 'Golden Sandstone Rooms'],
    images: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    ]
  },
  {
    id: 'prop_14',
    hostId: 'host_004',
    title: 'Wayanad Bamboo Forest Treehouse & Stream',
    tagline: 'Secluded bamboo treehouse suspended over natural mountain stream.',
    description: 'Immerse yourself in Wayanad wilderness. Features a bamboo treehouse built on twin ficus trees, natural stream dipping pool, organic spice farm tours, and Ayurvedic massage therapists.',
    price: 13800,
    cleaning: 1800,
    rating: 4.99,
    reviews: 33,
    city: 'Wayanad, Kerala',
    specs: { guests: 3, bedrooms: 1, beds: 1, baths: 1 },
    hostName: 'Mathew & Mini Varghese',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    amenities: ['Natural Stream Dip', 'Bamboo Treehouse', 'Spice Farm Tour', 'Ayurvedic Massage'],
    images: [
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    ]
  }
];
